### ISSUE TITLE
no eerors but jdk is not installed on target macchine

### ISSUE THREAD

**Issue by satheeshkv** [andrewrothstein/ansible-java-oracle-jdk#1]
I have installed the role and ran the play book.  Here is the output I got but i dont see the java is installed on the target machine.

1) please tell me where the java will install on the target? if I want to install on /opt, where I need to change and execute?

 PLAY [web] **************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************
ok: [192.168.137.131]

TASK [andrewrothstein.unarchive-deps : resolve platform specific vars] **************************************************************************************

TASK [andrewrothstein.unarchive-deps : install common pkgs...] **********************************************************************************************
ok: [192.168.137.131] => (item=unzip)
ok: [192.168.137.131] => (item=gzip)
ok: [192.168.137.131] => (item=bzip2)
ok: [192.168.137.131] => (item=tar)
ok: [192.168.137.131] => (item=xz)

TASK [andrewrothstein.alpine-glibc-shim : fix alpine] *******************************************************************************************************
skipping: [192.168.137.131]

TASK [andrewrothstein.java-oracle : resolve platform specific vars] *****************************************************************************************

TASK [andrewrothstein.java-oracle : include_tasks] **********************************************************************************************************
included: /opt/ansible/devops/roles/andrewrothstein.java-oracle/tasks/tgz.yml for 192.168.137.131

TASK [andrewrothstein.java-oracle : check for install..] ****************************************************************************************************
ok: [192.168.137.131]

TASK [andrewrothstein.java-oracle : download tgz...] ********************************************************************************************************
changed: [192.168.137.131]

TASK [andrewrothstein.java-oracle : unarchive....] **********************************************************************************************************
changed: [192.168.137.131]

TASK [andrewrothstein.java-oracle : cleanup] ****************************************************************************************************************
changed: [192.168.137.131]

TASK [andrewrothstein.java-oracle : link....] ***************************************************************************************************************
changed: [192.168.137.131]

TASK [andrewrothstein.java-oracle : add to default path and ease systemd integration...] ********************************************************************
changed: [192.168.137.131] => (item={u'd': u'/etc/profile.d', u'f': u'java-oracle.sh'})
changed: [192.168.137.131] => (item={u'd': u'/usr/local/jdk1.8.0_162', u'f': u'java-oracle.env'})

TASK [andrewrothstein.java-oracle-jdk : add JDK_HOME to the default environment and ease systemd integration...] ********************************************
changed: [192.168.137.131] => (item={u'd': u'/etc/profile.d', u'f': u'oracle-jdk.sh'})
changed: [192.168.137.131] => (item={u'd': u'/usr/local/java', u'f': u'oracle-jdk.env'})

PLAY RECAP **************************************************************************************************************************************************
192.168.137.131            : ok=10   changed=6    unreachable=0    failed=0

**Comment by andrewrothstein** [comment]
Look under /usr/local/java. If you launch a login bash shell it should be added to your path.
```
[arothste@bootcfg ~]$ docker run --rm -it quay.io/andrewrothstein/ansible-java-oracle-jdk:ubuntu_xenial bash -l -c 'which java; java -version'
/usr/local/java/bin/java
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```
The `java_oracle_parent_install_dir` role var defines the parent directory for the install. The default is `/usr/local`.
